### ISSUE TITLE
Cannot find nuget package

### ISSUE THREAD

**Issue by nohros** [Shuttle/Shuttle.Core.SimpleInjector#1]
I did not found the corresponding nuget package. This component is still alive?

**Comment by eben-roux** [comment]
This component is part of the v8.0 release of Shuttle and has not been released yet.  I'm going to try and do so over the weekend.

**Comment by eben-roux** [comment]
Unfortunately, I did not manage to get to a state where I can release.  I am aiming for this coming weekend...

**Comment by nohros** [comment]
Do you need any help with coding?

**Comment by eben-roux** [comment]
This is actually complete now and ready for use:

- [Nuget Package](https://www.nuget.org/packages/Shuttle.Core.SimpleInjector/)
- [Repository](https://github.com/Shuttle/Shuttle.Core.SimpleInjector)

If you find any issues you are of course more than welcome to send a pull request.

Actually this reminds me... I need to create releases on the repositories.
